Repository PopFri/FrontEnd, pull requests merged in 2025-06, with the labels that each got.

#27 [FEAT] #26 회원가입 창 성별, 나이 입력 구현
  src/components/login/contents.jsx
  src/components/myPage/Profile.jsx
  src/styles/login/contents.css
Labels: :sparkles: feature

#30 [FEAT] #29 instance 메서드 userId 전송값 변경
  src/App.jsx
Labels: :sparkles: feature, :recycle: refactor

#34 [FIX] #33 폰트 변경
  src/styles/fonts/fonts.css
Labels: :bug: bugfix

#37 [FEAT] #35 로그 데이터 추가 정보 전달
  src/pages/Discovery.jsx
  src/pages/Home.jsx
  src/pages/MovieDetailPage.jsx
  src/pages/MovieDiscoveryPage.jsx
  src/pages/MyPage.jsx
Labels: :sparkles: feature

#40 [FEAT] #39 제공 업체 로고 링크 설정
  src/components/discoveryFilm/DiscoveryMovie.jsx
  src/components/movieDetail/PosterSection.jsx
  src/styles/movieDetail/TrailerSection.css
Labels: :sparkles: feature, :recycle: refactor
